AWSTemplateFormatVersion: '2010-09-09'
Description: ASG with TG and LB

Resources:
  HTTPSecGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Instance to allow HTTP access via port 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  SSHSecGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Instance to allow SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'
  HTTPminALBFrontEnd:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: LoadBalancer to allow HTTP access to TargetGroup 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
#   minLoadBalancer:
#   minTargetGroup:
#   minListerner:
  minLaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateName: !Sub '${AWS::StackName}-launch-template-for-auto-scaling'
      LaunchTemplateData:
        SecurityGroupIds:
          - !GetAtt HTTPSecGroup.GroupId
          - !GetAtt SSHSecGroup.GroupId
        ImageId: ami-0c1bc246476a5572b
        InstanceType: t2.micro
        KeyName: MyDemoKey1
        UserData:
          Fn::Base64: 
            !Sub |
              #!/bin/bash
              yum update -y
              amazon-linux-extras install nginx1 -y
              amazon-linux-extras install epel -y
              yum update -y
              yum install stress -y
              systemctl start nginx
              systemctl enable nginx
              echo whazzaaaaaa!!!! from $(hostname -f) > /usr/share/nginx/html/index.html
  minASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref minLaunchTemplate
        Version: !GetAtt minLaunchTemplate.LatestVersionNumber
      AvailabilityZones:
        Fn::GetAZs: ''
      MaxSize: '3'
      MinSize: '1'
      DesiredCapacity: '1'
      VPCZoneIdentifier:   
        - subnet-03b2b746e62f3345d
        - subnet-0ff59f869374c89ac
        - subnet-0b3372cb27bb57b45
      MetricsCollection: 
        - Granularity: "1Minute"
          Metrics: 
            - "GroupMinSize"
            - "GroupMaxSize"
#   minASGAutoScalePolicy:
#     Type: AWS::AutoScaling::ScalingPolicy
#     Properties: 
#       AutoScalingGroupName: !Ref minASG
#       PolicyType: "SimpleScaling"
#       AdjustmentType: "ChangeInCapacity"
#       ScalingAdjustment: 1
  minScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName:
        Ref: minASG
      Cooldown: '60'
      ScalingAdjustment: '1'
  minScaleDownPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName:
        Ref: minASG
      Cooldown: '60'
      ScalingAdjustment: "-1"
  CPUAlarmHigh:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Scale-up if CPU > 80% for 5 minutes
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: '300'
      EvaluationPeriods: '1'
      Threshold: '80'
      AlarmActions:
      - Ref: minScaleUpPolicy
      Dimensions:
      - Name: AutoScalingGroupName
        Value:
          Ref: minASG
      ComparisonOperator: GreaterThanThreshold
  CPUAlarmLow:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Scale-down if CPU < 70% for 5 minutes
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: '300'
      EvaluationPeriods: '1'
      Threshold: '70'
      AlarmActions:
      - Ref: minScaleDownPolicy
      Dimensions:
      - Name: AutoScalingGroupName
        Value:
          Ref: minASG
      ComparisonOperator: LessThanThreshold